services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./docker-init:/docker-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        pid=$!
        sleep 80
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -C -i /docker-init/init.sql
        wait $pid

  app:
    build: .
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    restart: on-failure
    entrypoint: /bin/sh
    command:
      - -c
      - |
        sleep 90
        java -jar /app/app.jar

volumes:
  sqlserver-data: