spring.application.name=loansystem

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=book_loan_system;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa_user
spring.datasource.password=bddroque
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# DEAR RECRUITER: This key is only for development/demo purposes.
# In the production environment, this is handled via Environment Variables.
security.jwt-key=esta_es_una_clave_de_prueba_12345
security.jwt.expiration-time=3600000
security.jwt.issuer=library-loan-system