spring.application.name=loansystem

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

security.jwt-key=${JWT_SECRET}
security.jwt.issuer=library-loan-system
security.jwt.expiration-time=3600000